import { Routes } from '@angular/router';
import { authGuard } from './core/auth.guard';

export const routes: Routes = [
  { path: '', pathMatch: 'full', redirectTo: 'home' },
  { path: 'home', loadComponent: () => import('./pages/home/home.component').then(m => m.HomeComponent) },
  { path: 'login', loadComponent: () => import('./pages/auth/login.component').then(m => m.LoginComponent) },
  { path: 'register', loadComponent: () => import('./pages/auth/register.component').then(m => m.RegisterComponent) },
  { path: 'forgot', loadComponent: () => import('./pages/auth/forgot.component').then(m => m.ForgotComponent) },
  { path: 'about', loadComponent: () => import('./pages/about/about.component').then(m => m.AboutComponent) },
  { path: 'search', loadComponent: () => import('./pages/shop/search-results.component').then(m => m.SearchResultsComponent) },
  { path: 'shop', loadComponent: () => import('./pages/shop/shop.component').then(m => m.ShopComponent) },
  { path: 'shops/:id', loadComponent: () => import('./pages/shop/shop-detail.component').then(m => m.ShopDetailComponent) },
  { path: 'products/:id', loadComponent: () => import('./pages/shop/product-detail.component').then(m => m.ProductDetailComponent) },
  { path: 'products/:id/comments', loadComponent: () => import('./pages/shop/product-comments.component').then(m => m.ProductCommentsComponent) },
  { path: 'products/:id/ai-chat', loadComponent: () => import('./pages/shop/ai-chat.component').then(m => m.AiChatComponent) },
  { path: 'complaints', canActivate: [authGuard(['user', 'merchant', 'admin'])], loadComponent: () => import('./pages/complaints/complaints.component').then(m => m.ComplaintsComponent) },
  { path: 'complaints/:id', canActivate: [authGuard(['user', 'merchant', 'admin'])], loadComponent: () => import('./pages/complaints/complaint-detail.component').then(m => m.ComplaintDetailComponent) },
  { path: 'messages', canActivate: [authGuard(['user', 'merchant', 'admin'])], loadComponent: () => import('./pages/user/messages.component').then(m => m.MessagesComponent) },
  { path: 'messages/:thread', canActivate: [authGuard(['user', 'merchant', 'admin'])], loadComponent: () => import('./pages/user/message-thread.component').then(m => m.MessageThreadComponent) },
  { path: 'friends/add', canActivate: [authGuard(['user'])], loadComponent: () => import('./pages/user/add-friend.component').then(m => m.AddFriendComponent) },
  { path: 'cart', canActivate: [authGuard(['user'])], loadComponent: () => import('./pages/user/cart.component').then(m => m.CartComponent) },
  { path: 'profile', canActivate: [authGuard(['user'])], loadComponent: () => import('./pages/user/profile.component').then(m => m.ProfileComponent) },
  { path: 'favorites', canActivate: [authGuard(['user'])], loadComponent: () => import('./pages/user/favorites.component').then(m => m.FavoritesComponent) },
  { path: 'reviews', canActivate: [authGuard(['user'])], loadComponent: () => import('./pages/user/reviews.component').then(m => m.ReviewsComponent) },
  { path: 'data', canActivate: [authGuard(['user'])], loadComponent: () => import('./pages/user/data.component').then(m => m.DataComponent) },
  { path: 'addresses', canActivate: [authGuard(['user'])], loadComponent: () => import('./pages/user/addresses.component').then(m => m.AddressesComponent) },
  { path: 'settings', canActivate: [authGuard(['user'])], loadComponent: () => import('./pages/user/settings.component').then(m => m.SettingsComponent) },
  { path: 'orders/:id/pay', canActivate: [authGuard(['user'])], loadComponent: () => import('./pages/user/payment.component').then(m => m.PaymentComponent) },
  { path: 'orders/:id/detail', canActivate: [authGuard(['user'])], loadComponent: () => import('./pages/user/order-detail.component').then(m => m.OrderDetailComponent) },
  { path: 'orders', canActivate: [authGuard(['user'])], loadComponent: () => import('./pages/user/orders.component').then(m => m.OrdersComponent) },
  { path: 'merchant', canActivate: [authGuard(['merchant', 'admin'])], loadComponent: () => import('./pages/merchant/merchant-dashboard.component').then(m => m.MerchantDashboardComponent) },
  { path: 'merchant/profile', canActivate: [authGuard(['merchant', 'admin'])], loadComponent: () => import('./pages/merchant/merchant-profile.component').then(m => m.MerchantProfileComponent) },
  { path: 'merchant/shop-layout', canActivate: [authGuard(['merchant', 'admin'])], loadComponent: () => import('./pages/merchant/merchant-shop-layout.component').then(m => m.MerchantShopLayoutComponent) },
  { path: 'merchant/products', canActivate: [authGuard(['merchant', 'admin'])], loadComponent: () => import('./pages/merchant/merchant-products.component').then(m => m.MerchantProductsComponent) },
  { path: 'merchant/products/new', canActivate: [authGuard(['merchant', 'admin'])], loadComponent: () => import('./pages/merchant/merchant-product-form.component').then(m => m.MerchantProductFormComponent) },
  { path: 'merchant/products/:id/edit', canActivate: [authGuard(['merchant', 'admin'])], loadComponent: () => import('./pages/merchant/merchant-product-form.component').then(m => m.MerchantProductFormComponent) },
  { path: 'merchant/after-sales', canActivate: [authGuard(['merchant', 'admin'])], loadComponent: () => import('./pages/merchant/merchant-after-sales.component').then(m => m.MerchantAfterSalesComponent) },
  { path: 'merchant/settings', canActivate: [authGuard(['merchant', 'admin'])], loadComponent: () => import('./pages/user/settings.component').then(m => m.SettingsComponent) },
  { path: 'merchant/data/:panel', canActivate: [authGuard(['merchant', 'admin'])], loadComponent: () => import('./pages/merchant/merchant-data-detail.component').then(m => m.MerchantDataDetailComponent) },
  { path: 'admin', canActivate: [authGuard(['admin'])], loadComponent: () => import('./pages/admin/admin-dashboard.component').then(m => m.AdminDashboardComponent) },
  { path: 'admin/logs', canActivate: [authGuard(['admin'])], loadComponent: () => import('./pages/admin/admin-system-logs.component').then(m => m.AdminSystemLogsComponent) },
  { path: 'admin/data/:panel', canActivate: [authGuard(['admin'])], loadComponent: () => import('./pages/admin/admin-data-detail.component').then(m => m.AdminDataDetailComponent) },
  { path: '**', redirectTo: 'shop' }
];
